//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contrat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contrat()
        {
            this.Risque_diver = new HashSet<Risque_diver>();
        }
    
        public string N_contrat { get; set; }
        public string Code_produit { get; set; }
        public Nullable<int> N_siret { get; set; }
        public string CIN { get; set; }
        public Nullable<System.DateTime> Date_début { get; set; }
        public Nullable<System.DateTime> Date_fin { get; set; }
        public string Description { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Entreprise Entreprise { get; set; }
        public virtual Produit Produit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Risque_diver> Risque_diver { get; set; }
    }
}
