//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class habitation1
    {
        public string Code_habitation { get; set; }
        public string CIN { get; set; }
        public string Genre { get; set; }
        public string Résidence { get; set; }
        public string Estimation_de_biens { get; set; }
        public Nullable<int> Nombre_de_sinistre { get; set; }
        public string Durée { get; set; }
        public Nullable<System.DateTime> Date_début { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
